### ISSUE TITLE
NetrcParseError: bad toplevel token

### ISSUE THREAD

**Issue by maudeplucker** [kobotoolbox/xls-import#18]
Hello, 

I am tranferring files from kobo.ifrc.org to kobonew.ifrc.org. 
I am seeking assistance in solving the error _NetrcParseError: bad toplevel token_ when calling `$ python post.py`

<img width="956" alt="Screenshot 2021-05-31 at 12 48 15" src="https://user-images.githubusercontent.com/84128324/120183165-a1378380-c20f-11eb-953f-e0e091cd5f5c.png">

The `HOME.netrc` file looks like this

<img width="763" alt="Screenshot 2021-05-31 at 12 48 38" src="https://user-images.githubusercontent.com/84128324/120183168-a1d01a00-c20f-11eb-84ab-845af8468efa.png">

Any suggestions to solve this error are appreciated. I am using Python 3.8. 
Thank you in advance. 

Maude

**Comment by jnm** [comment]
Sorry we didn't notice this sooner. I'm glad you were able to get help with this internally.

(for anyone else who arrives here: make sure you save the `.netrc` file as plain text, not RTF)

Internal discussion: https://chat.kobotoolbox.org/#narrow/stream/15-IFRC/topic/Need.20help.20migrating.20a.20project/near/68670
