### ISSUE TITLE
Handle dates

### ISSUE THREAD

**Issue by mroswell** [kobotoolbox/xls-import#4]
Dates could be a mix of text (if starter spreadsheet is output) and floats 
From the xlrd documentation ( http://xlrd.readthedocs.io/en/latest/dates.html ):

> Dates are not stored as a separate data type; they are stored as floating point numbers and you have to rely on:
> - the “number format” applied to them in Excel and/or
> - knowing which cells are supposed to have dates in them.

Currently the xls2xml script prints out date text either 
- if the date was generated by the XML, or 
- if the date was hand-prepended with an apostrophe (signaling test)

Otherwise it shows up as a number.

**Comment by jnm** [comment]
My suggestion is that the dates-as-text be passed through without modification, and the dates-as-floats be sussed out with `cell.ctype == xlrd.XL_CELL_DATE` and `xlrd.xldate.xldate_as_datetime(cell.value, workbook.datemode)`. I'll include an IPython session of me playing with this that includes some fun things like `??` to read the definition of an object's class.

I took the [example project mentioned earlier in Flowdock](https://github.com/kobotoolbox/xls-import/files/1556977/different.data.types.zip) and then manually added some date columns to `data export.xlsx` using LibreOffice Calc: [modified data export.xlsx](https://github.com/kobotoolbox/xls-import/files/1556978/modified.data.export.xlsx). These columns have headers prefixed with `LibO_`. Then, opening `modified data export.xlsx` with xlrd:
```

(e)john@scrappy:/tmp/different data types$ ipython
WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
Python 2.7.6 (default, Nov 23 2017, 15:49:48) 
Type "copyright", "credits" or "license" for more information.

IPython 1.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import xlrd

In [2]: workbook = xlrd.open_workbook('modified data export.xlsx')

In [3]: sheet = workbook.sheets()[0]

In [4]: zip(sheet.row(0), sheet.row(1))
Out[4]: 
[(text:u'start', text:u'2017-12-13T11:34:36.728-05'),
 (text:u'end', text:u'2017-12-13T11:34:57.296-05'),
 (text:u'Text', text:u'Greetings!'),
 (text:u'Date', text:u'2017-12-13'),
 (text:u'Time', text:u'11:34:00.000-05'),
 (text:u'Date_time', text:u'2017-12-13T11:34:00.000-05'),
 (text:u'LibO_date', xldate:43082.0),
 (text:u'LibO_time', xldate:0.627083333333333),
 (text:u'LibO_date_time', xldate:43082.6270833333),
 (text:u'Integer', text:u'123'),
 (text:u'Decimal', text:u'456.789'),
 (text:u'__version__', text:u'vqqeo9ike7huBhjDYAbXUZ'),
 (text:u'_id', number:7333975.0),
 (text:u'_uuid', text:u'3745cdef-66e3-4d84-9892-c4ad45a68ed0'),
 (text:u'_submission_time', text:u'2017-12-13T16:35:56'),
 (text:u'_index', number:1.0)]

In [5]: sheet.row(1)[8]
Out[5]: xldate:43082.6270833333

In [6]: cell = sheet.row(1)[8]

In [7]: cell.
cell.ctype     cell.dump      cell.value     cell.xf_index  

In [7]: cell.ctype
Out[7]: 3

In [8]: cell??
Type:       Cell
String Form:xldate:43082.6270833333
File:       /tmp/e/lib/python2.7/site-packages/xlrd/sheet.py
Source:
class Cell(BaseObject):
    """
    Contains the data for one cell.

    .. warning::
      You don't call this class yourself. You access :class:`Cell` objects
      via methods of the :class:`Sheet` object(s) that you found in the
      :class:`~xlrd.book.Book` object that was returned when you called
      :func:`~xlrd.open_workbook`

    Cell objects have three attributes: ``ctype`` is an int, ``value``
    (which depends on ``ctype``) and ``xf_index``.
    If ``formatting_info`` is not enabled when the workbook is opened,
    ``xf_index`` will be ``None``.

    The following table describes the types of cells and how their values
    are represented in Python.

    .. raw:: html

        <table border="1" cellpadding="7">
        <tr>
        <th>Type symbol</th>
        <th>Type number</th>
        <th>Python value</th>
        </tr>
        <tr>
        <td>XL_CELL_EMPTY</td>
        <td align="center">0</td>
        <td>empty string u''</td>
        </tr>
        <tr>
        <td>XL_CELL_TEXT</td>
        <td align="center">1</td>
        <td>a Unicode string</td>
        </tr>
        <tr>
        <td>XL_CELL_NUMBER</td>
        <td align="center">2</td>
        <td>float</td>
        </tr>
        <tr>
        <td>XL_CELL_DATE</td>
        <td align="center">3</td>
        <td>float</td>
        </tr>
        <tr>
        <td>XL_CELL_BOOLEAN</td>
        <td align="center">4</td>
        <td>int; 1 means TRUE, 0 means FALSE</td>
        </tr>
        <tr>
        <td>XL_CELL_ERROR</td>
        <td align="center">5</td>
        <td>int representing internal Excel codes; for a text representation,
        refer to the supplied dictionary error_text_from_code</td>
        </tr>
        <tr>
        <td>XL_CELL_BLANK</td>
        <td align="center">6</td>
        <td>empty string u''. Note: this type will appear only when
        open_workbook(..., formatting_info=True) is used.</td>
        </tr>
        </table>
    """

    __slots__ = ['ctype', 'value', 'xf_index']

    def __init__(self, ctype, value, xf_index=None):
        self.ctype = ctype
        self.value = value
        self.xf_index = xf_index

    def __repr__(self):
        if self.xf_index is None:
            return "%s:%r" % (ctype_text[self.ctype], self.value)
        else:
            return "%s:%r (XF:%r)" % (ctype_text[self.ctype], self.value, self.xf_index)

In [9]: xlrd.XL_CELL_DATE
Out[9]: 3

In [10]: cell.ctype == xlrd.XL_CELL_DATE
Out[10]: True

In [11]: xlrd.xldate.xldate_as_datetime(cell.value, workbook.datemode)
Out[11]: datetime.datetime(2017, 12, 13, 15, 3)

In [12]: # but what about the time without a date?

In [13]: zip(sheet.row(0), sheet.row(1))
Out[13]: 
[(text:u'start', text:u'2017-12-13T11:34:36.728-05'),
 (text:u'end', text:u'2017-12-13T11:34:57.296-05'),
 (text:u'Text', text:u'Greetings!'),
 (text:u'Date', text:u'2017-12-13'),
 (text:u'Time', text:u'11:34:00.000-05'),
 (text:u'Date_time', text:u'2017-12-13T11:34:00.000-05'),
 (text:u'LibO_date', xldate:43082.0),
 (text:u'LibO_time', xldate:0.627083333333333),
 (text:u'LibO_date_time', xldate:43082.6270833333),
 (text:u'Integer', text:u'123'),
 (text:u'Decimal', text:u'456.789'),
 (text:u'__version__', text:u'vqqeo9ike7huBhjDYAbXUZ'),
 (text:u'_id', number:7333975.0),
 (text:u'_uuid', text:u'3745cdef-66e3-4d84-9892-c4ad45a68ed0'),
 (text:u'_submission_time', text:u'2017-12-13T16:35:56'),
 (text:u'_index', number:1.0)]

In [14]: time_cell = sheet.row(1)[7]

In [15]: time_cell
Out[15]: xldate:0.627083333333333

In [16]: time_cell.ctype
Out[16]: 3

In [17]: xlrd.xldate.xldate_as_datetime(time_cell.value, workbook.datemode)
Out[17]: datetime.datetime(1899, 12, 31, 15, 3)

In [18]: # yikes, but see separately-included screenshot
```
The 1899 actually corresponds to what LibreOffice shows when I change the format of the time cell: 
![image](https://user-images.githubusercontent.com/2085013/33961651-e0737546-e01c-11e7-9c9f-867cfd239c8d.png)

I hope this is helpful, but I don't know:
* If Microsoft Excel behaves differently;
* If there's a need to detect and specially handle bare times (@tinok?);
* If a different library like openpyxl would allow us to discern formatting info better (I did see that xlrd can read `formatting_info` from xls but [cannot read it from xlsx](http://xlrd.readthedocs.io/en/latest/api.html#xlrd.open_workbook));
* If we should assume that Excel times-as-floats are in UTC (the text representations seem to include timezone offsets);
* ...

**Comment by mroswell** [comment]
It's a lot to digest, but I suspect the example assumes that you know that the field is supposed to be a date? My understanding is that xlrd is treating it as a number, unless
someone manually enters a single quote in the beginning of each cell, in which case it's considered text. My past experience--not a current test--signals that when I set the format of cells to be text, it still is likely to output data fields as numbers, unless they have the preceding single quote. Will mark to test.

**Comment by mroswell** [comment]
UPDATE: I see now that xlrd does know if a cell is a date. (the part I quoted above led me to believe otherwise.)
http://xlrd.readthedocs.io/en/latest/api.html#xlrd.sheet.Cell
However, if a date column (that we don't know by default is a date column) has both text and dates, we'll need to be careful to correctly sort out.

**Comment by mroswell** [comment]
BTW, thanks for all the detail above!

**Comment by tinok** [comment]
@jnm @mroswell Yes we can expect that the data be formatted in just one particular way, no need to support multiple formats. 

For example, we can require that the user formats them as text, following the example `11:34:00.000-05`

**Comment by mroswell** [comment]
Closing issue; Users are required to add dates and times as text.
