### ISSUE TITLE
Remove requirement on field order of __version__ to determine which fields are data

### ISSUE THREAD

**Issue by mroswell** [kobotoolbox/xls-import#6]
Currently the script loops through each row cell  until it hits the `__version__` field. Change this to ensure that the fields:

`start`, `end`, `__version__`, `_id`, `_uuid`, `_submission_time`, `_parent_table_name`, `_parent_index`

- may be in any order
- are not included as data

**Comment by tinok** [comment]
@mroswell `start` and `end` are meta questions filled automatically by the client software normally.  A complete list of these is listed under 'meta questions' on http://xlsform.org/ref-table/

**Comment by mroswell** [comment]
Add column order requirement to instructions
