### ISSUE TITLE
Handle select_multiple

### ISSUE THREAD

**Issue by mroswell** [kobotoolbox/xls-import#7]
select_multiples are identified in the excel spreadsheet by fields containing a slash that have the same select fieldname.

These should appear in the output XML as follows (space-delimited inside the fieldname element):
` <Which_activities_do_you_enjoy>hiking cross_country_ backpacking</Which_activities_do_you_enjoy>`
 
Not sure if this issue: https://github.com/kobotoolbox/formpack/issues/60 impacts this task. My guess is that it doesn't, but worth asking to confirm.

**Comment by jnm** [comment]
Along the lines of https://github.com/kobotoolbox/xls-import/issues/6, the columns may be in any order.

@tinok, do we need to support question groups?

**Comment by tinok** [comment]
@jnm @mroswell  I think we should be able to import questions that are in groups. The headers could be formatted in whatever way we want so as to make the import task easier (e.g. they could omit the parent group names, and requiring that each question is unique to the form).

**Comment by jnm** [comment]
OK, per https://www.flowdock.com/app/kobotoolbox/kobo/threads/wToUqG1u8fk1htNvaO_3PUz-7Tr, we can require that the import spreadsheet use `/` as the `select_multiple` delimiter and some other character as the group delimiter.
