### ISSUE TITLE
Support groups

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/xls-import#8]
If we had a question named `sunglasses` in a group called `eyewear`, the XML requires: `<eyewear><sunglasses>prada</eyewear></sunglasses>`.

We can require the input XLS to use a character _other than_ `/` as the group delimiter. Tino [says](https://www.flowdock.com/app/kobotoolbox/kobo/messages/1080453): 
> Since XML headers don't allow almost any special characters, we could use ~ or $ etc

c.f. #7

**Comment by mroswell** [comment]
I presume instead of:
```
<eyewear><sunglasses>prada</eyewear></sunglasses>
```
This should read:
```
<eyewear><sunglasses>prada</sunglasses></eyewear>
```
Is that correct?

**Comment by jnm** [comment]
Yep, my mistake!

**Comment by mroswell** [comment]
Currently the script handles repeating groups, where the repeat data appears in another sheet. I gather this issue is for groups that don't repeat (where the data appears in the initial sheet?)

**Comment by mroswell** [comment]
Planning to use "::" as delimiter. See also #10

**Comment by mroswell** [comment]
Commit: d3771fe
